
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package io.renren.modules.logistics.util.shiprate;

import javax.jws.WebService;
import javax.xml.ws.Holder;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-06-08T18:02:43.218+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(
                      serviceName = "ShipRate",
                      portName = "ShipRateSOAP",
                      targetNamespace = "http://www.example.org/ShipRate/",
                      wsdlLocation = "http://www.sfcservice.com/ishipsvc/web-service?wsdl",
                      endpointInterface = "io.renren.modules.logistics.util.shiprate.ShipRate")

public class ShipRateImpl implements ShipRate {

    private static final Logger LOG = Logger.getLogger(ShipRateImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getCountries(org.example.shiprate.GetCountriesRequest  parameters )*
     */
    public Countries getCountries(GetCountriesRequest parameters) {
        LOG.info("Executing operation getCountries");
        System.out.println(parameters);
        try {
            Countries _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }







    /* *//* *//**//* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getFeeByOrderCode(org.example.shiprate.HeaderRequest  headerRequest ,)java.lang.String  orderCode ,)java.lang.String  ask ,)java.lang.String  sysTime ,)java.lang.String  msg ,)java.lang.String  baseFee ,)java.lang.String  regFee ,)java.lang.String  dealFee ,)java.lang.String  insurance ,)java.lang.String  totalFee ,)java.lang.String  currencyCode ,)java.lang.String  chargebackTime ,)java.lang.String  chargebackWorkDay ,)java.lang.String  shipTypeCode ,)java.lang.String  subShipType ,)java.lang.String  waybillCode ,)java.lang.String  discount ,)java.util.List<org.example.shiprate.OtherFee>  otherFee ,)java.lang.String  originBaseFee ,)java.lang.String  originAddons ,)java.lang.String  stDealFee ,)java.lang.String  stRegFee ,)java.lang.String  feeWeight )*
     */
    public Map<String, String> getFeeByOrderCode(HeaderRequest headerRequest, Holder<String> orderCode, Holder<String> ask, Holder<String> sysTime, Holder<String> msg, Holder<String> baseFee, Holder<String> regFee, Holder<String> dealFee, Holder<String> insurance, Holder<String> totalFee, Holder<String> currencyCode, Holder<String> chargebackTime, Holder<String> chargebackWorkDay, Holder<String> shipTypeCode, Holder<String> subShipType, Holder<String> waybillCode, Holder<String> discount, Holder<List<OtherFee>> otherFee, Holder<String> originBaseFee, Holder<String> originAddons, Holder<String> stDealFee, Holder<String> stRegFee, Holder<String> feeWeight) {
        Map<String,String> map=new HashMap<>();
        LOG.info("Executing operation getFeeByOrderCode");
        System.out.println(headerRequest);
        System.out.println(orderCode.value);
        try {
            String askValue = "";
            ask.value = askValue;
            map.put("ask",ask.toString());

            String sysTimeValue = "";
            sysTime.value = sysTimeValue;
            map.put("sysTime",sysTime.toString());

            String msgValue = "";
            msg.value = msgValue;
            String baseFeeValue = "";
            baseFee.value = baseFeeValue;
            map.put("baseFee",baseFee.toString());

            String regFeeValue = "";
            regFee.value = regFeeValue;
            map.put("regFee",regFee.toString());

            String dealFeeValue = "";
            dealFee.value = dealFeeValue;
            map.put("dealFee",dealFee.toString());

            String insuranceValue = "";
            insurance.value = insuranceValue;
            map.put("insurance",insurance.toString());

            String totalFeeValue = "";
            totalFee.value = totalFeeValue;
            System.out.println("总运费:"+totalFee.value);
            map.put("totalFee",totalFee.toString());
            String currencyCodeValue = "";
            currencyCode.value = currencyCodeValue;
            map.put("stDealFee",stDealFee.toString());

            String chargebackTimeValue = "";
            chargebackTime.value = chargebackTimeValue;
            map.put("stDealFee",stDealFee.toString());

            String chargebackWorkDayValue = "";
            chargebackWorkDay.value = chargebackWorkDayValue;
            map.put("stDealFee",stDealFee.toString());

            String shipTypeCodeValue = "";
            shipTypeCode.value = shipTypeCodeValue;
            map.put("stDealFee",stDealFee.toString());

            String subShipTypeValue = "";
            subShipType.value = subShipTypeValue;
            map.put("stDealFee",stDealFee.toString());

            String waybillCodeValue = "";
            waybillCode.value = waybillCodeValue;
            map.put("stDealFee",stDealFee.toString());

            String discountValue = "";
            discount.value = discountValue;
            map.put("stDealFee",stDealFee.toString());

            java.util.List<OtherFee> otherFeeValue = null;
            otherFee.value = otherFeeValue;
            map.put("stDealFee",stDealFee.toString());

            String originBaseFeeValue = "";
            originBaseFee.value = originBaseFeeValue;
            map.put("stDealFee",stDealFee.toString());

            String originAddonsValue = "";
            originAddons.value = originAddonsValue;
            map.put("stDealFee",stDealFee.toString());

            String stDealFeeValue = "";
            stDealFee.value = stDealFeeValue;
            map.put("stDealFee",stDealFee.toString());

            String stRegFeeValue = "";
            stRegFee.value = stRegFeeValue;
            map.put("stRegFee",stRegFee.toString());
            String feeWeightValue = "";
            feeWeight.value = feeWeightValue;
            map.put("feeWeight",feeWeight.toString());
        } catch (Exception ex) {
            map.put("code","false");
            map.put("msg","网络发生故障异常!");
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        return map;
    }



    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getShipTypes(org.example.shiprate.GetShipTypesRequest  parameters )*
     */
    public Shiptypes getShipTypes(GetShipTypesRequest parameters) {
        LOG.info("Executing operation getShipTypes");
        System.out.println(parameters);
        try {
            Shiptypes _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#updateOrderStatus(org.example.shiprate.HeaderRequest  headerRequest ,)org.example.shiprate.UpdateOrderStatusInfoArray  updateOrderInfo ,)java.lang.String  orderCode ,)java.lang.String  ask ,)java.lang.String  message ,)javax.xml.datatype.XMLGregorianCalendar  time )*
     */
    public void updateOrderStatus(HeaderRequest headerRequest, UpdateOrderStatusInfoArray updateOrderInfo, String orderCode, Holder<String> ask, Holder<String> message, Holder<javax.xml.datatype.XMLGregorianCalendar> time) {
        LOG.info("Executing operation updateOrderStatus");
        System.out.println(headerRequest);
        System.out.println(updateOrderInfo);
        System.out.println(orderCode);
        try {
            String askValue = "";
            ask.value = askValue;
            String messageValue = "";
            message.value = messageValue;
            javax.xml.datatype.XMLGregorianCalendar timeValue = null;
            time.value = timeValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getRatesByType(org.example.shiprate.HeaderRequest  headerRequest ,)org.example.shiprate.GetRatesByTypeRequestInfo  ratesRequestInfo )*
     */
    public java.util.List<Rate> getRatesByType(HeaderRequest headerRequest,GetRatesByTypeRequestInfo ratesRequestInfo) {
        LOG.info("Executing operation getRatesByType");
        System.out.println(headerRequest);
        System.out.println(ratesRequestInfo);
        try {
            java.util.List<Rate> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getRateByMode(org.example.shiprate.GetRateByMode  parameters )*
     */
    public Rate getRateByMode(GetRateByMode parameters) {
        LOG.info("Executing operation getRateByMode");
        System.out.println(parameters);
        try {
            Rate _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getRates(org.example.shiprate.HeaderRequest  headerRequest ,)org.example.shiprate.GetRatesRequestInfo  ratesRequestInfo )*
     */
    public java.util.List<Rate> getRates(HeaderRequest headerRequest,GetRatesRequestInfo ratesRequestInfo) {
        LOG.info("Executing operation getRates");
        System.out.println(headerRequest);
        System.out.println(ratesRequestInfo);
        try {
            java.util.List<Rate> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#addOrder(org.example.shiprate.AddOrderRequest  parameters )*
     */
    public AddOrderResponse addOrder(AddOrderRequest parameters) {
        LOG.info("Executing operation addOrder");
        System.out.println(parameters);
        try {
            AddOrderResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#updateOrderVolumeWeight(org.example.shiprate.UpdateOrderVolumeWeightRequest  parameters )*
     */
    public UpdateOrderVolumeWeightResponse updateOrderVolumeWeight(UpdateOrderVolumeWeightRequest parameters) {
        LOG.info("Executing operation updateOrderVolumeWeight");
        System.out.println(parameters);
        try {
            UpdateOrderVolumeWeightResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#searchOrder(org.example.shiprate.SearchOrderRequest  parameters )*
     */
    public SearchOrderResponse searchOrder(SearchOrderRequest parameters) {
        LOG.info("Executing operation searchOrder");
        System.out.println(parameters);
        try {
            SearchOrderResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#getClassTypes(org.example.shiprate.GetClassTypesRequest  parameters )*
     */
    public Classtypes getClassTypes(GetClassTypesRequest parameters) {
        LOG.info("Executing operation getClassTypes");
        System.out.println(parameters);
        try {
            Classtypes _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#updateOrder(org.example.shiprate.HeaderRequest  headerRequest ,)org.example.shiprate.AddOrderRequestInfoArray  updateOrderInfo ,)java.lang.String  orderCode ,)java.lang.String  ask ,)java.lang.String  message ,)javax.xml.datatype.XMLGregorianCalendar  time ,)java.lang.String  alert )*
     */
    public void updateOrder(HeaderRequest headerRequest, AddOrderRequestInfoArray updateOrderInfo, String orderCode, Holder<String> ask, Holder<String> message, Holder<javax.xml.datatype.XMLGregorianCalendar> time, Holder<String> alert) {
        LOG.info("Executing operation updateOrder");
        System.out.println(headerRequest);
        System.out.println(updateOrderInfo);
        System.out.println(orderCode);
        try {
            String askValue = "";
            ask.value = askValue;
            String messageValue = "";
            message.value = messageValue;
            javax.xml.datatype.XMLGregorianCalendar timeValue = null;
            time.value = timeValue;
            String alertValue = "";
            alert.value = alertValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#batchAddOrders(org.example.shiprate.HeaderRequest  headerRequest ,)java.util.List<org.example.shiprate.AddOrderRequestInfoArray>  orders ,)java.lang.String  ask ,)java.lang.String  operatingTime ,)java.lang.String  message ,)java.util.List<org.example.shiprate.AddOrderResponseData>  data )*
     */
    public void batchAddOrders(HeaderRequest headerRequest, java.util.List<AddOrderRequestInfoArray> orders, Holder<String> ask, Holder<String> operatingTime, Holder<String> message, Holder<java.util.List<AddOrderResponseData>> data) {
        LOG.info("Executing operation batchAddOrders");
        System.out.println(headerRequest);
        System.out.println(orders);
        try {
            String askValue = "";
            ask.value = askValue;
            String operatingTimeValue = "";
            operatingTime.value = operatingTimeValue;
            String messageValue = "";
            message.value = messageValue;
            java.util.List<AddOrderResponseData> dataValue = null;
            data.value = dataValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.example.shiprate.ShipRate#reSetLabel(org.example.shiprate.HeaderRequest  headerRequest ,)org.example.shiprate.ReSetLabelInfoArray  reSetLabelInfo ,)java.lang.String  orderCode ,)java.lang.String  ask ,)java.lang.String  message ,)java.lang.String  trackingNumber ,)javax.xml.datatype.XMLGregorianCalendar  time )*
     */
    public void reSetLabel(HeaderRequest headerRequest, ReSetLabelInfoArray reSetLabelInfo, String orderCode, Holder<String> ask, Holder<String> message, Holder<String> trackingNumber, Holder<javax.xml.datatype.XMLGregorianCalendar> time) {
        LOG.info("Executing operation reSetLabel");
        System.out.println(headerRequest);
        System.out.println(reSetLabelInfo);
        System.out.println(orderCode);
        try {
            String askValue = "";
            ask.value = askValue;
            String messageValue = "";
            message.value = messageValue;
            String trackingNumberValue = "";
            trackingNumber.value = trackingNumberValue;
            javax.xml.datatype.XMLGregorianCalendar timeValue = null;
            time.value = timeValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
